### ISSUE TITLE
A few issues and requests

### ISSUE THREAD

**Issue by guyzk** [natintosh/intl-phone-number-input#8]
Great work on being one of the first to finally add a phone input package!
A few issues and requests:
1) The validation is not forwarded to the form so if the phone input is invalid (especially when there is more than 1 phone input) it is not reflected in the form validation (form will remain valid even if phone input is invalid).
2) When an error text is provided the country code is not center aligned with the phone input which gives it an unprofessional look.
3) Please provide a way to style the input text.
4) Better support for RTL apps (my apps have several languages supported, some of which are RTL.
5) Return phone number object which will return both the phone number and the country code and maybe the ISO code.

**Comment by natintosh** [comment]
> Return phone number object which will return both the phone number and the country code and maybe the ISO code.

I like this idea rather than returning string of phone number, country code and country 2 letter code, I'll pass a single that contains all this

> Please provide a way to style the input text.

You could always style the text field with either of this two constructor

```
InternationalPhoneNumberInput.withCustomDecoration
InternationalPhoneNumberInput.withCustomBorder
```

> When an error text is provided the country code is not center aligned with the phone input which gives it an unprofessional look.

Help needed on this I need further information on this 

> The validation is not forwarded to the form so if the phone input is invalid (especially when there is more than 1 phone input) it is not reflected in the form validation (form will remain valid even if phone input is invalid).

Do you mean a Form validation as in TextFormField validation

> Better support for RTL apps (my apps have several languages supported, some of which are RTL.
I'll look into this

Thanks for your feedback @guyzk 👍👍👍

**Comment by guyzk** [comment]
Thanks for the quick response!

>I like this idea rather than returning string of phone number, country code and country 2 letter code, I'll pass a single Object that contains all this

Great! Maybe you could pass this object also in the "onSubmit" function.

> When an error text is provided the country code is not center aligned with the phone input which gives it an unprofessional look.
> Help needed on this I need further information on this

I think in the row that contains the dropdown and the input widget you should add the following:
`crossAxisAlignment: CrossAxisAlignment.start,`

> You could always style the text field with either of this two constructor
> InternationalPhoneNumberInput.withCustomDecoration
> InternationalPhoneNumberInput.withCustomBorder

The text in the input widget it not in the decoration object but as a "style" attribute in the TextField (or TextFormField). This will require you to add another attribute ("textStyle"?) which will be passed to the TextField widget.

> Do you mean a Form validation as in TextFormField validation

Yes! I think it will be best to change to a TextFormField (you will have the "validator" attribute) and have the validation passed to the parenting form.

**Comment by guyzk** [comment]
@natintosh any update on whether any of the requests are planned to be implemented in the near future?

**Comment by VOIDCRUSHER** [comment]
Hi @natintosh,

I agree with @guyzk 's suggestion to use a TextFormField since phone number input fields are usually used as part of a larger form. Is there any chance this would could be rolled into the next release?

As general feedback, I really appreciate all the great work. I like how you're exposing the InputDecoration for the TextField because it allows for more control over the form appearance. I am noting that, since the InputDecoration passed into InternationalPhoneNumberInput overrides the InputBorder and hintText constructor parameters, it could be confusing to include both. Might these be marked as Deprecated for future use since this is handled already by InputDecoration?

**Comment by natintosh** [comment]
> @natintosh any update on whether any of the requests are planned to be implemented in the near future?

Hi @guyzk, I'm totally working on it it just that I've been busy with office work the last [update](https://github.com/natintosh/intl-phone-number-input/commit/ab7845f95e492ed90709335712191d842a0ffb59) I add PhoneNumber object that you reference and I currently have a local branch that have fixes to issues you raised except the AR localization

**Comment by natintosh** [comment]
> since the InputDecoration passed into InternationalPhoneNumberInput overrides the InputBorder and hintText constructor parameters, it could be confusing to include both. Might these be marked as Deprecated for future use since this is handled already by InputDecoration?

Oh it took a while for me to understand what you were trying to say here you are right but I can't mark it as deprecated because I'm currently exposing a constructor called with withCustomDecoration that does't accept hintText. I think I need to find a way to hide that from the the default constructor

**Comment by guyzk** [comment]
Thanks for the update.
The RTL issue is really killing me so that I am not able to use the package at the moment.

**Comment by guyzk** [comment]
Posted a solution for the RTL issue in the following issue
https://github.com/natintosh/intl-phone-number-input/issues/16
Closing this one as all other features have been imlemented
Thanks!!
